version: '3'
services:
  #   [Official](https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html)
  #  filebeat:
  #    image: docker.elastic.co/beats/filebeat:${ELASTIC_STACK_VERSION}
  #    volumes:
  #      - ./mount/filebeat/usr/share/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #      - ./mount/filebeat/import/:/var/log/import
  #      - /var/run/docker.sock:/var/run/docker.sock:ro
  #    depends_on:
  #      - elasticsearch
  # [Official](https://www.elastic.co/guide/en/logstash/current/docker-config.html)
  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_STACK_VERSION}
    volumes:
      - ./mount/logstash/usr/share/logstash/pipeline/import-alb-access-log.conf:/usr/share/logstash/pipeline/import-alb-access-log.conf
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
  # [Official](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_STACK_VERSION}
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - xpack.security.enabled=false # ローカルなので認証をOFFにしておく
      - action.destructive_requires_name=false # index削除する時に hoge-*のようにワイルドカードで操作できるようにするやつ
    volumes:
      - es-data:/usr/share/elasticsearch/data/
    ports:
      - "9200:9200"
      - "9300:9300"
  # [Official](https://www.elastic.co/guide/en/kibana/current/docker.html)
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_STACK_VERSION}
    environment:
      - I18N_LOCALE=ja-JP # Kibanaを日本語で表示する
    #volumes:
    #  - ./mount/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
volumes:
  es-data:
    driver: local
