#filebeat.config:
#  modules:
#    path: ${path.config}/modules.d/*.yml
#    reload.enabled: false

filebeat.inputs:
  - type: filestream
    paths:
      - /var/log/import/*.json
    parsers:
      - ndjson:
          expand_keys: true
          add_error_key: true

processors:
  - decode_json_fields:
      fields: [ "message" ]
  - timestamp:
      field: timestamp
      layouts:
        - "UNIX_MS"
#      target_field: target_timestamp
#      timezone: "Asia/Tokyo"
#  - drop_fields:
#      fields: ["source","host.name"]

#processors:
#  - decode_json_fields:
#      fields: ["message"]
#      process_array: false
#      max_depth: 10
#      target: ""
#      overwrite_keys: false
#      add_error_key: true
#  - add_cloud_metadata: ~
#  - add_docker_metadata: ~

output.elasticsearch:
  hosts: [ elasticsearch:9200 ]
  index: "aws-waf-access-log-%{+yyyy.MM.dd}"

# https://www.elastic.co/guide/en/beats/filebeat/current/change-index-name.html
setup.template:
  enabled: false # JSONを読み込ませるならtemplateは不要なのでfalseにしておく

monitoring.enabled: false
