filebeat.inputs:
  - type: filestream
    paths:
      - /var/log/import/*.json
    parsers:
      - ndjson:
          keys_under_root: true
          message_key: inner

#processors:
#  - decode_json_fields:
#      fields: [ "message" ]
#  - timestamp:
#      field: time
#      target_field: test_time
#      timezone: "Asia/Tokyo"
#      layouts:
#        - '2006-01-02T15:04:05.999999+07:00'
#        - '2006-01-02T15:04:05.999999Z07:00'
#        - '2006-01-02T15:04:05.999999999Z07:00'
#      test:
#        - '2022-04-11T16:36:15.378330+09:00'

#index: "%{[agent.name]}-applogs-%{+yyyy.MM.dd}"

#filebeat.config:
#  modules:
#    path: ${path.config}/modules.d/*.yml
#    reload.enabled: false

#processors:
#  - decode_json_fields:
#      fields: ["message"]
#      process_array: false
#      max_depth: 10
#      target: ""
#      overwrite_keys: false
#      add_error_key: true
#  - add_cloud_metadata: ~
#  - add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'

monitoring.enabled: false
